# Generated by Django 4.2.5 on 2023-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_num', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=64)),
                ('Lname', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='database.course')),
            ],
        ),
    ]
